---
layout: single
title:  "예외처리"
categories: JAVA
---

# 예외처리 Exception
### 예외: 프로그램이 실행되는 동안에 발생하는 예기치 않는 에러를 의미
## 사용하는 이유: 비 정상적인 종료를 막기 위해서 사용
 * 파일 입출력, 키보드 입출력 , DB연동 
 * java.lang , java io, java.sql. 패키지에 자주 보는   클래스가  있다. 
## 예외처리 클래스 
* java.lang.Excepiton : 0으로 나눌때

* ArrayIndexOutOfBoundsException : 배열의 범위를 벗어났을때

* NumberFormatException : 숫자외의 값을 사용할때

* NullPointerException : 객체를 생성하지   않고 멤버변수나 메소드를 호출할때

* IOException : 입출력에 관련된 예외

* FileNotFoundException : 파일이 없을때 발생

* SQLException : 데이터베이스 관련 예외
* 예외 처리 클래스(java.lang 패키지에 있다.)
* Class Exception 이 최상위 클래스 이다. 
* 예외 클래스는 기본 생성자로 구성한다. 와 매개변수가 (String 형) 생성자 
 ### 예외 처리 형식

```````````````java
 1.  가장 기본 
   try{
	예외가 발생할 가능성이 있는 문장;
   }catch(예외클래스명  매개변수){
	예외 메시지;
   }

2. 
   try{
	예외가 발생할 가능성이 있는 문장;
   }catch(예외클래스명 매개변수){
	예외 메시지;
   }catch(예외클래스명 매개변수){
	예외 메시지;
   }

3. 
   try{
	예외가 발생할 가능성이 있는 문장;
   }catch(예외클래스명 매개변수){
	예외 메시지;
   }finally{
	//주로 파일을 닫을때, 데이터베이스 연결 끊을때 사용됨
               예외가 발생하든, 발생하지 않든 무조건 실행됨;
   }

4.  class Test{   
       public void check() throws Exception{

       }

       public static void main(String[] args){
	  try{        
		Test t = new Test();
        		t.check();
	  }catch(Exception e){
	  }
       }
    }

5. class Test{
    public void check() throws ArrayIndexOutOfBoundsException {
       
		for( int i=0 ; i<10 ; i++ ) {
		  // 예외를 던짐(프로그래머가 예외를 발생시킴)
			if( i == 3 ){ 
			  throw new ArrayIndexOutOfBoundsException();
			}			
		}
    }	
    public static void main( String[] args ) {
		Test t = new Test();	
	try {
	    t.check();
	} catch ( ArrayIndexOutOfBoundsException ab ) {	    
	    ab.printStackTrace();
	}
   }
````````````````
 ## 예문 예외 처리를 되지 않았을 경우 
 ## 예문  예외 처리 했을 때

``````````````````````````````````````````````````java
package p2022_07_11;
// 예외 처리를 되지 않았을 경우
public class DivideZeroException {
    public static void main( String[] args ) {
    	
	// int type의 변수 선언
 	int b = 20;
	int a = 0;

	// 두 수의 나눗셈 결과를 구한다
	int c = b/a;    // 예외발생:프로그램이 비정상적으로 멈추게 된다. 
	int total = a + b;
	int sub = b-a;
	
	System.out.println( c );
   }
}
	
// 안전하게 프로그램 종료를 하기 위해서 예외 처리를 한다. 
package p2022_07_11;

public class DivideZeroExceptionHandling {
    public static void main( String[] args ) {
    	
//  예외처리 1.: try~catch 구문으로 예외처리
//    	try{
//    		예외가 발생할 가능성이 있는 문장;
//     }catch(예외클래스명  매개변수){
//    		  예외 메시지;
//    		   }	
//  2.예외가 발생하지 않으면, try안의 내용만 실행하고, catch아랫쪽 내용은 실행되지 않는다. 
//  3 예외가 발생하면 예외가 발생한 라인 아랫쪽은 내용을 실행하지 않고, catch 쪽으로 예외를 던진다.
    	
    	  	
	// int type의 변수 선언
 	int b = 20;
	int a = 0;
	int c = 0;

	// 두 수의 나눗셈 결과를 구한다

	try {
		c = b/a;     //예외처리 발생 : 아랫쪽이 실행되지 않는다. 
		System.out.println("실행안됨");
		int total = a + b;
		int sub = b-a;
		
	} catch ( ArithmeticException ae ) {
		a = 2;  // 예외 처리 한 것을 catch가 받아서, 수정하는 작업을 한다. 
		c = b/a;
	}
		System.out.println( c ); //10
    }
}
````````````````````````````````````````````````````````
## 예문 Exception (최상위 클래스 )

```````````````````````````java
package p2022_07_11;

// 예외처리
//catch 구문에서 예외처리 클래스를 잘 모를때 예외처리 클래스 중에서
//최상위 클래스인 Exception 클래스로 모든 자식클래스의 예외를 받을 수 있다. 
public class DivideZeroExceptionHandling1 {
    public static void main( String[] args ) {
    	
	// int type의 변수 선언
 	int b = 20;
	int a = 0;
	int c = 0;

	// 두 수의 나눗셈 결과를 구한다

	try {
		c = b/a;
		int total = a + b;
		int sub = b-a;
		
	} catch ( Exception e ) {  // 예외처리:  최상위클래스(Exception)
		a = 2;
		c = b/a;
	}

		System.out.println( c );
    }
}

//예외처리:  최상위클래스(Exception)은 모두 클래스의 예외처리가 가능한다. 

```````````````````````````````````````````
##  예문: 예외 상황별로 맞는 예외를 catch에 던지를떄 사용한다. 
* ArrayIndexOutOfBoundsException
* ArithmeticException

```````````````````````java
package p2022_07_11;
// 예외 상황별로 맞는 예외를 catch에 던지를떄 사용한다. 

public class MultiExceptionHandling {
    public static void main( String[] args ) {
		
	int value = 20;
	int div = 0;
	int[] intArray = { 1, 2, 3 };
// intArray[0]=1   intArray [1]=2   intArray[2]=3
	try {
//		   int arrayValue = intArray[4];    // 예외발생 
//		  System.out.println( arrayValue );	

	      // 두수의 나눗셈을 구함
	      int result = value / div;         // 예외발생 
	      System.out.println( result );

		  // 배열의 특정 값을 저장
          int arrayValue = intArray[4];
		  System.out.println( arrayValue );	    

	    } catch ( ArithmeticException ae ) {		
			System.out.println( ae.toString() );
			System.out.println("0으로 나눌수 없습니다.");
	    } catch ( ArrayIndexOutOfBoundsException ai ) {
			ai.printStackTrace();
			System.out.println("배열의 범위를 벗어 났습니다.");
	    } 
    }    
}
//ArrayIndexOutOfBoundsException : 배열의 범위를 벗어났을때

```````````````````````````````````````````````
## 예문 :예외처리 클래스를 여러 가지 클래스로 사용할때  Exception 가장 마지막으로 써야 한다. 

`````````````````````````java
package p2022_07_11;

  public class ExceptionEx3 {

	public static void main(String[] args) {
		int var = 50;
		// args[0]="5" 예외발생 하지 않음
		// args[0]="a" 예외 발생 
		// args[0]="0" 예외 발생 	
		try{
			int data = Integer.parseInt(args[0]); 
		
			System.out.println(var/data);
		   
		// 1.Exception 예외 클래스가 하위 예외 클래스들을 
		// 2.모두 가지고 있기 때문에 먼저 정의해서는 안된다.
//		   3.catch로 예외처리를 할때 	Exception 클래스는 마지막으로 사용해야 한다. 
         
//			}catch(Exception e){      
//			System.out.println("Exception !!");	
			
		}catch(NumberFormatException ne){
			System.out.println("숫자가 아닙니다.");
		}catch(ArithmeticException ae){
			System.out.println("0으로 나눌순 없죠?");
		}catch(Exception e){      // 가장 마지막으로 Exception을 써야 한다. 
		  System.out.println("Exception !!");	
		}
		  System.out.println("프로그램 종료!");		
	}
  }
//예외처리 클래스를 여러 가지 클래스로 사용할때  Exception 가장 마지막으로 써야 한다. 

```````````````````````````````````````````````````````````````
## 3.예문 try~ catch~ finally  DB연동을 할때 많이 사용된다. 
  *  1.finally 안에 들어 있는 내용은 예외가 발생하든, 발생하지 않든 무조건 실행
  * 2.보통finally 안에 들어가는 내용은 파일을 닫거나, 데이터베이스 연결을 끊는 내용
  *   ex) file.close() con.cldose()

```````````````````````````````````````````
package p2022_07_11;

public class MultiExceptionHandling1 {
    public static void main( String[] args ) {
    	
 
// 1.finally 안에 들어 있는 내용은 예외가 발생하든, 발생하지 않든 무조건 실행
// 2.보통finally 안에 들어가는 내용은 파일을 닫거나,데이터베이스 연결을 끊는 내용
//  ex) file.close() con.cldose()
    	
	int value = 20;
	int div = 10;

	int[] intArray = { 1, 2, 3 };

	try {
	    // 두수의 나눗셈을 구함
	    int result = value / div;      //예외발생
	    System.out.println( result );

	    // 배열의 특정 값을 저장
            int arrayValue = intArray[2];
			System.out.println( arrayValue );

	    } catch ( ArithmeticException ae ) {
			System.out.println( ae.toString() );

	    } catch ( ArrayIndexOutOfBoundsException ai ) {
			ai.printStackTrace();

	    } finally {
	    	System.out.println("예외가 발생했음!");

	    }	 
    }    
}
``````````````````````````````````````````````````````
## 예문4.  Throws  자주 사용한다. 
* 메소드에서 처리하지 않은 예외를 호출한 곳으로 떠 넘기는 역할
* 동일한 메소드가 여러개가 있을때 사용된다. 
*  각 메소드 마다. throws을 쓰지 않고, 
*  메소드 호출 한 곳에 throws을 던져서 메인 메소드 한테 한꺼 번에 예외 처리 한다. 

````````````````````````````````````java
package p2022_07_11;

public class ThrowsExceptionHandling1 {
	//occurException()를 호출한 곳으로 예외처리를 양도 하겠다는 의미
    public void occurException() throws ArithmeticException {
	 
		// ArithmethicException 발생
		int result = 3/0;          //예외발생
		System.out.println( result );	 
    }

    public static void main( String[] args ) {
		// 객체를 생성
ThrowsExceptionHandling1 te = new ThrowsExceptionHandling1();

	// try-catch 블록으로 예외 처리
	try {
		te.occurException(); // 메소드 호출 
	} catch ( ArithmeticException ae ) {   // Exception ae 사용 가능 하다. 
		System.out.println( "Exception이 발생 : " + ae.toString() );
		System.out.println( "0으로 나눌 수 없습니다." );
	}
    }
}

// Exception으로 던지면 Exception 으로 받아야 하고, 
//자식 ArithmeticException 던지면, Exception 으로 사용가능하다.
// 각 메소드 마다 예외 처리 하지않고, 예외처리 하는 메소드에 한꺼 번에 한다. 
```````````````````````````````````````````````````````````````
## 예문5. 
* 강제로 예외를 처리 할때 throws 받는 곳은 메인 메소드한테 전달한다. 
* 예외를 발생시키는 시점을 임의로 조건식으로 조절할 수있다.
* throw new연산자 객체 생성을 하면, 강제로 예외를 발생한다.

``````````````````````java
package p2022_07_11;

public class ThrowException {

	public void exceptionMethod()throws ArrayIndexOutOfBoundsException {
        // 배열 선언
		int[] intA = { 1, 2, 3, 4 };   

		// 배열의 저장된 값을 출력
		for( int i=0 ; i<10 ; i++ ) {
		    // 예외를 던짐(프로그래머가 예외를 발생시킴)
		  if( i == 4 ) throw new ArrayIndexOutOfBoundsException();
		 // 예외를 발생시키는 시점을 임의로 조건식으로 조절할 수있다. 
			System.out.println( intA[i] );
		}
    }

    public static void main( String[] args ) {
		ThrowException te = new ThrowException();
	
	try {
	    te.exceptionMethod();
	} catch ( ArrayIndexOutOfBoundsException ab ) {
	    System.out.println( "배열의 index를 초과했습니다." );
	    ab.printStackTrace();
	}

    }//main() end
}
````````````````````````````````````````````````````````````````````````````
## 예문6. 사용자 정의 예외처리 방법 (예외처리 클래스 만들어서 사용)
*  예외 클래스는 기본 생성자로 구성한다. 와 매개변수가 (String 형) 생성자 

```````````````````````java
package p2022_07_11;

public class UserDefineException extends Exception {
//            사용자 정의 예외 클래스 
    // 기본 생성자
    public UserDefineException() {
    }

    // 인수를 하나 받아들이는 생성자
    public UserDefineException( String information ) {
		// Exception 클래스의 생성자 호출
		super( information ); //부모클래스의 매개변수 생성자 호출 
    }
}


package p2022_07_11;

public class UserExceptionTest {
	
    // Exception을 호출한 메소드로 던짐
    public void printNumber() throws UserDefineException {
	for( int i=0 ; i<10 ; i++ ) {
	    // Excpetion을 발생시킴
	    if( i == 5 ) throw new UserDefineException( "사용자가 정의한 Exception입니다" );
		System.out.println( i );
	}
    }

    public static void main( String[] args ) {
	UserExceptionTest uet = new UserExceptionTest();
		
	try {
		uet.printNumber();
	} catch ( UserDefineException ue ) {
		System.out.println( ue.toString() );
	}
    }
}
p



























